opam-version: "2.0"
synopsis: "Elliptic Curve Cryptography generated with ECCKiila/Fiat"
description: """
An implementation of key exchange (ECDH) and digital signature (ECDSA)
algorithms using code from ECCKiila/Fiat
(<https://gitlab.com/nisec/ecckiila>).

The curves BrainpoolP256r1, BrainpoolP384r1, BrainpoolP512r1 are
implemented by this package.
"""
maintainer: "Sven Anderson <sven@anderson.de>"
authors: [
  "See AUTHORS file"
]
license: "MIT"
homepage: "https://github.com/Nitrokey/nethsm-crypto"
doc: "https://ocaml.org/p/nethsm-crypto/latest/doc/index.html"
bug-reports: "https://github.com/Nitrokey/nethsm-crypto/issues"
depends: [
  "nethsm-crypto" {=version}
]
build: [
  ["dune" "subst"] {dev}
  ["dune" "build" "-p" name "-j" jobs]
]
dev-repo: "git+https://github.com/Nitrokey/nethsm-crypto.git"
tags: []
x-maintenance-intent: [ "(latest)" ]
