(library
 (name nethsm_crypto_nist)
 (public_name nethsm-crypto-nist)
 (modules Nethsm_crypto_nist)
 (libraries nethsm-crypto eqaf mirage-crypto-rng digestif)
 (foreign_stubs
  (language c)
  (names p256_stubs np256_stubs p384_stubs np384_stubs p521_stubs np521_stubs)
  (include_dirs ../src/native)
  (flags
   (:standard -DNDEBUG)
   (:include cflags_optimized.sexp))))

(library
 (name nethsm_crypto_secp256k1)
 (public_name nethsm-crypto-secp256k1)
 (modules Nethsm_crypto_secp256k1)
 (libraries nethsm-crypto eqaf mirage-crypto-rng digestif)
 (foreign_stubs
  (language c)
  (names secp256k1_stubs nsecp256k1_stubs)
  (include_dirs ../src/native)
  (flags
   (:standard -DNDEBUG)
   (:include cflags_optimized.sexp))))

(library
 (name nethsm_crypto_brainpool)
 (public_name nethsm-crypto-brainpool)
 (modules Nethsm_crypto_brainpool)
 (libraries nethsm-crypto eqaf mirage-crypto-rng digestif)
 (foreign_stubs
  (language c)
  (names brainpoolp256_stubs nbrainpoolp256_stubs brainpoolp384_stubs
    nbrainpoolp384_stubs brainpoolp512_stubs nbrainpoolp512_stubs)
  (include_dirs ../src/native)
  (flags
   (:standard -DNDEBUG)
   (:include cflags_optimized.sexp))))

(library
 (name nethsm_crypto)
 (public_name nethsm-crypto)
 (modules Nethsm_crypto)
 (libraries mirage-crypto-rng))

(env
 (dev
  (c_flags
   (:include cflags_warn.sexp))))

(include_subdirs unqualified)

(rule
 (targets cflags_optimized.sexp cflags_warn.sexp)
 (action
  (run ../config/cfg.exe)))
